import type { ConstructionKnowledgeRecord } from './types';

export const CONSTRUCTION_KNOWLEDGE: ConstructionKnowledgeRecord[] = [
  {
    id: 'const-modified-mixing-temp',
    key: 'mixing-temperature',
    label: '改性沥青拌和温度',
    source: 'JTG F40 / 改性沥青施工控制',
    sourceVersion: '内置建议',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    materialSystems: ['modified', 'sma', 'rap'],
    condition: 'SBS/SBR 等改性沥青混合料',
    range: { lo: 160, hi: 165 },
    unit: '°C',
    severity: 'warning',
    message: '改性沥青拌和温度通常控制在 160°C~165°C，并应结合供应商黏温曲线修正。',
  },
  {
    id: 'const-high-modulus-discharge-temp',
    key: 'discharge-temperature',
    label: '高模量混合料出料温度',
    source: '高模量沥青混合料技术规程',
    sourceVersion: '内置建议',
    applicableMixTypes: ['HM-20'],
    applicableMethods: 'all',
    materialSystems: ['high-modulus'],
    condition: '高模量沥青混合料施工',
    range: { lo: 175, hi: 185 },
    unit: '°C',
    severity: 'warning',
    message: '高模量沥青混合料出料温度建议控制在 175°C~185°C。',
  },
  {
    id: 'const-high-modulus-waste-temp',
    key: 'waste-temperature',
    label: '高模量混合料废弃温度',
    source: '高模量沥青混合料技术规程',
    sourceVersion: '内置建议',
    applicableMixTypes: ['HM-20'],
    applicableMethods: 'all',
    materialSystems: ['high-modulus'],
    condition: '高模量沥青混合料施工',
    value: 195,
    unit: '°C',
    severity: 'blocking',
    message: '高模量混合料超过 195°C 应按废弃温度控制，避免老化和性能衰减。',
  },
  {
    id: 'const-rap-mixing-time',
    key: 'rap-mixing-time',
    label: '厂拌热再生拌和时间',
    source: '厂拌热再生技术规程',
    sourceVersion: '内置建议',
    applicableMixTypes: ['RAP-AC-20'],
    applicableMethods: ['marshall'],
    materialSystems: ['rap'],
    condition: 'RAP 厂拌热再生混合料',
    range: { lo: 5, hi: 10 },
    unit: 's',
    severity: 'warning',
    message: '厂拌热再生工程宜延长拌和时间 5~10s，以促进新旧沥青融合。',
  },
  {
    id: 'const-bond-coat',
    key: 'bond-coat',
    label: '层间粘结材料喷洒量',
    source: '沥青路面层间结合施工控制',
    sourceVersion: '内置建议',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    materialSystems: 'all',
    condition: '双层或多层沥青铺装',
    range: { lo: 0.3, hi: 0.5 },
    unit: 'L/m2',
    severity: 'info',
    message: '双层铺装建议喷洒 0.3~0.5 L/m2 改性乳化沥青作为粘层或透层，实际用量按现场试洒确定。',
  },
];
