import type { KnowledgeRecord } from './types';

export const MATERIAL_KNOWLEDGE: KnowledgeRecord[] = [
  {
    id: 'mat-base-asphalt',
    label: '基质沥青',
    source: 'JTG F40',
    sourceVersion: '2004',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    condition: '70A、90A、110A 等道路石油沥青',
    severity: 'info',
    message: '基质沥青应录入针入度、软化点、延度和批次报告，密度采用实测值优先。',
  },
  {
    id: 'mat-polymer-modified',
    label: '聚合物改性沥青',
    source: 'JTG F40',
    sourceVersion: '2004',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    condition: 'SBS、SBR 等改性沥青材料体系',
    severity: 'info',
    message: '改性沥青应提高施工温度控制精度，并重点校核车辙、水稳定和低温性能。',
  },
  {
    id: 'mat-high-modulus-additive',
    label: '高模量外掺剂',
    source: '高模量沥青混合料技术规程',
    sourceVersion: '项目指定版本',
    applicableMixTypes: ['HM-20'],
    applicableMethods: 'all',
    condition: '高模量沥青混合料或掺加高模量剂时',
    severity: 'warning',
    message: '高模量外掺剂应记录掺量、投放方式和供应商指标，并补充动稳定度与低温弯曲破坏应变校核。',
  },
  {
    id: 'mat-fiber-stabilizer',
    label: '纤维稳定剂',
    source: 'SMA 专项设计要求',
    sourceVersion: '项目指定版本',
    applicableMixTypes: ['SMA-13'],
    applicableMethods: 'all',
    condition: 'SMA 或高沥青用量骨架密实结构',
    severity: 'warning',
    message: '纤维稳定剂应记录类型和掺量，并通过谢伦堡析漏试验验证玛蹄脂稳定性。',
  },
  {
    id: 'mat-rap',
    label: 'RAP 再生沥青混合料回收料',
    source: '厂拌热再生技术规程',
    sourceVersion: '项目指定版本',
    applicableMixTypes: ['RAP-AC-20'],
    applicableMethods: ['marshall'],
    condition: '厂拌热再生混合料使用 RAP 时',
    range: { lo: 0, hi: 3 },
    unit: 'RAP 含水率 %',
    severity: 'blocking',
    message: 'RAP 含水率宜控制不大于 3%，最大颗粒粒径宜不大于 26.5mm。',
  },
];
