import type { PerformanceKnowledgeRecord } from './types';

export const PERFORMANCE_KNOWLEDGE: PerformanceKnowledgeRecord[] = [
  {
    id: 'perf-water-stability',
    key: 'waterStability',
    label: '浸水马歇尔残留稳定度',
    source: 'JTG F40',
    sourceVersion: '2004',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    materialSystems: 'all',
    condition: '常规路用性能验证',
    range: { lo: 85, hi: null },
    unit: '%',
    comparator: 'gte',
    severity: 'blocking',
    message: '浸水马歇尔残留稳定度通常不小于 85%，未满足时应复核沥青用量、矿粉比例和抗剥落措施。',
  },
  {
    id: 'perf-freeze-thaw',
    key: 'freezeThaw',
    label: '冻融劈裂残留强度比',
    source: 'JTG F40',
    sourceVersion: '2004',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    materialSystems: 'all',
    condition: '水稳定性专项验证',
    range: { lo: 80, hi: null },
    unit: '%',
    comparator: 'gte',
    severity: 'blocking',
    message: '冻融劈裂残留强度比通常不小于 80%，潮湿或冰冻地区应重点关注。',
  },
  {
    id: 'perf-rutting-modified',
    key: 'rutting',
    label: '车辙动稳定度',
    source: 'JTG F40 / 项目性能要求',
    sourceVersion: '内置阈值',
    applicableMixTypes: ['AC-13', 'AC-16', 'AC-20', 'AC-25', 'RAP-AC-20'],
    applicableMethods: 'all',
    materialSystems: ['modified'],
    condition: '普通改性沥青混合料',
    range: { lo: 3500, hi: null },
    unit: '次/mm',
    comparator: 'gte',
    severity: 'warning',
    message: '项目暂定要求：普通改性沥青混合料动稳定度建议不小于 3500 次/mm，需由项目要求确认后再作为阻断项。',
  },
  {
    id: 'perf-rutting-sma',
    key: 'rutting',
    label: '车辙动稳定度',
    source: 'SMA 专项性能要求',
    sourceVersion: '内置阈值',
    applicableMixTypes: ['SMA-13'],
    applicableMethods: 'all',
    materialSystems: ['sma'],
    condition: 'SMA 混合料',
    range: { lo: 5500, hi: null },
    unit: '次/mm',
    comparator: 'gte',
    severity: 'blocking',
    message: 'SMA 混合料动稳定度建议不小于 5500 次/mm。',
  },
  {
    id: 'perf-rutting-high-modulus',
    key: 'rutting',
    label: '车辙动稳定度',
    source: '高模量沥青混合料技术规程',
    sourceVersion: '内置阈值',
    applicableMixTypes: ['HM-20'],
    applicableMethods: 'all',
    materialSystems: ['high-modulus'],
    condition: '高模量沥青混合料，60°C、0.7MPa 条件',
    range: { lo: 6000, hi: null },
    unit: '次/mm',
    comparator: 'gte',
    severity: 'blocking',
    message: '高模量混合料动稳定度建议不小于 6000 次/mm。',
  },
  {
    id: 'perf-low-temp',
    key: 'lowTemperature',
    label: '低温弯曲破坏应变',
    source: 'JTG F40 / 高模量专项要求',
    sourceVersion: '内置阈值',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    materialSystems: 'all',
    condition: '低温抗裂性能验证',
    range: { lo: 2300, hi: null },
    unit: 'με',
    comparator: 'gte',
    severity: 'warning',
    message: '项目暂定要求：低温弯曲破坏应变建议不小于 2300 με，需由项目要求确认后再作为阻断项。',
  },
  {
    id: 'perf-schellenberg',
    key: 'schellenberg',
    label: '谢伦堡沥青析漏损失',
    source: 'SMA 专项性能要求',
    sourceVersion: '内置阈值',
    applicableMixTypes: ['SMA-13', 'OGFC-13'],
    applicableMethods: 'all',
    materialSystems: ['sma', 'modified'],
    condition: 'SMA/OGFC 玛蹄脂稳定性验证',
    range: { lo: 0, hi: 0.15 },
    unit: '%',
    comparator: 'lte',
    severity: 'blocking',
    message: '析漏损失应不大于 0.15%；改性沥青或高要求项目宜控制不大于 0.10%。',
  },
  {
    id: 'perf-cantabro',
    key: 'cantabro',
    label: '肯塔堡飞散损失',
    source: 'SMA/OGFC 专项性能要求',
    sourceVersion: '内置阈值',
    applicableMixTypes: ['SMA-13', 'OGFC-13'],
    applicableMethods: 'all',
    materialSystems: ['sma', 'modified'],
    condition: 'SMA/OGFC 耐久性验证',
    range: { lo: 0, hi: 15 },
    unit: '%',
    comparator: 'lte',
    severity: 'blocking',
    message: '飞散损失应不大于 15%；高要求项目宜控制不大于 10%。',
  },
  {
    id: 'perf-airport-cdf',
    key: 'cdf',
    label: '累积疲劳损伤因子 CDF',
    source: '民用机场沥青道面设计规范',
    sourceVersion: '项目指定版本',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    materialSystems: 'all',
    condition: '机场道面力学模型校核',
    range: { lo: 0, hi: 1.05 },
    unit: '',
    comparator: 'lte',
    severity: 'warning',
    message: '机场道面 CDF 应不大于 1.05；本应用仅记录校核结果，不自动建立力学模型。',
  },
];
