import type { KnowledgeRecord } from './types';

export const TERM_KNOWLEDGE: KnowledgeRecord[] = [
  {
    id: 'term-vv',
    label: 'VV 空隙率',
    source: 'JTG 试验规程体积指标',
    sourceVersion: '内置公式',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    condition: '已知毛体积密度与理论最大相对密度',
    value: 'VV = (1 - bulkDensity / Gmm) * 100',
    unit: '%',
    severity: 'info',
    message: '反映压实混合料内部空气体积比例，是 OAC 判定和耐久性控制的核心指标。',
  },
  {
    id: 'term-vma',
    label: 'VMA 矿料间隙率',
    source: 'JTG 试验规程体积指标',
    sourceVersion: '内置公式',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    condition: '已知油石比、混合料毛体积密度与合成矿料毛体积密度',
    value: 'VMA = [1 - bulkDensity / Gsb * 100 / (100 + asphaltContent)] * 100',
    unit: '%',
    severity: 'info',
    message: '反映矿料骨架可容纳沥青和空隙的总体积；SMA 与耐久性设计尤其敏感。',
  },
  {
    id: 'term-vfa',
    label: 'VFA 沥青饱和度',
    source: 'JTG 试验规程体积指标',
    sourceVersion: '内置公式',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    condition: '已知 VMA 与 VV',
    value: 'VFA = (VMA - VV) / VMA * 100',
    unit: '%',
    severity: 'info',
    message: '反映矿料间隙中被沥青填充的比例，用于防止沥青不足或过量。',
  },
  {
    id: 'term-gmm',
    label: 'Gmm 理论最大相对密度',
    source: 'JTG 试验规程体积指标',
    sourceVersion: '内置公式',
    applicableMixTypes: 'all',
    applicableMethods: 'all',
    condition: '可由真空法实测，也可用合成矿料表观密度与沥青密度估算',
    value: 'Gmm = (100 + asphaltContent) / (100 / Gsa + asphaltContent / Gb)',
    unit: 'g/cm3',
    severity: 'warning',
    message: '计算法仅供初步估算，正式报告应优先采用真空法实测理论最大密度。',
  },
  {
    id: 'term-vca',
    label: 'VCAmix / VCADRC 粗集料骨架间隙率',
    source: 'SMA 骨架嵌挤结构校核',
    sourceVersion: '内置规则',
    applicableMixTypes: ['SMA-13'],
    applicableMethods: 'all',
    condition: 'SMA 目标配合比设计时适用',
    value: 'VCAmix <= VCADRC',
    unit: '%',
    severity: 'blocking',
    message: 'SMA 应验证混合料中粗集料骨架间隙率不大于捣实粗集料骨架间隙率。',
  },
];
